version: 2

docker_login: &docker_login
  run:
    name: authentication
    command: |
      docker --version
      docker-compose --version
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

postgres_env: &postgres_env
  environment:
    # The defined vars the postgres containers use
    - POSTGRES_USER: clux
    - POSTGRES_DB: postgres
    - POSTGRES_PASSWORD: foobar
    # Hacky host ip for the diesel-cli container that is not using compose:
    - POSTGRES_DB_URL: 0.0.0.0

workflows:
  version: 2
  flow:
    jobs:
      - musl_build
      - unit_test
      - integration_test:
          requires:
            - musl_build
      - docker_push:
          requires:
            - musl_build
            - integration_test
          filters:
            branches:
              only:
                - master
jobs:
  musl_build:
    docker:
      - image: clux/muslrust:nightly
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - store_artifacts:
          path: target/x86_64-unknown-linux-musl/release/webapp
          destination: webapp
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - webapp

  unit_test:
    docker:
      - image: clux/muslrust:nightly
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - run: cargo doc --no-deps

  integration_test:
    machine:
      enabled: true
      docker_layer_caching: true
    <<: *postgres_env
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: docker-compose up -d db
      - run: sleep 10
      - run: make migrate
      - run: docker-compose up -d web
      - run: sleep 2
      - run: make test
      - run:
          name: Debug
          when: on_fail
          command: docker-compose logs

  docker_push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - <<: *docker_login
      - run: make build-docker
      - run: make tag-latest
      - run: make tag-semver

# TODO: clippy + rustfmt on merge
