version: 2
jobs:
  build:
    docker:
      - image: clux/muslrust:nightly
    working_directory: ~/webapp-rs
    steps:
      #- save_cache:
      #    key: cargo.lock-{{ checksum "Cargo.lock" }}
      #    paths:
      #      - target
      - run: cargo build --release

#  test:
#    docker:
#      - image: clux/muslrust:nightly
#        environment:
#          DATABASE_URL: postgres://root@localhost/circle_test
#      - image: circleci/postgres:9-alpine-ram
