version: 2
workflows:
  version: 2
  compile_build_and_test:
    jobs:
      - compile_app
      - build_image
#      - test_compose
jobs:
  compile_app:
    docker:
      - image: clux/muslrust:night
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
  build_image:
    machine:
      services:
        - docker
    steps:
      - checkout
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - docker build -t clux/webapp .
#  test_compose:
#    docker:
#      - image: clux/webapp-rs
#      - image: circleci/postgres:9-alpine-ram
#    working_directory: /volume
#    steps:
#      - checkout
#      - run: echo "TODO: diesel migration run"
#      - run: make test

#    environment:
#        DATABASE_URL: postgres://root@localhost/circle_test

# TODO: clippy + rustfmt on merge
