version: 2
jobs:
  build:
    docker:
      - image: clux/muslrust:nightly
      - save_cache:
          key: cargo.lock-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - run:
          name: build musl release
          command: cargo build --release
