version: 2
jobs:
  compile:
    docker:
      - image: clux/muslrust:night
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
  build:
    steps:
      - checkout
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - docker build -t clux/webapp .
  test:
    docker:
      - image: clux/webapp-rs
      - image: circleci/postgres:9-alpine-ram
    working_directory: /volume
    environment:
        DATABASE_URL: postgres://root@localhost/circle_test
    steps:
      - checkout
      - run: echo "TODO: diesel migration run"
      - run: make test

workflows:
  version: 2
  compile_build_and_test:
    jobs:
      - compile
      - build
      - test

# TODO: clippy + rustfmt on merge
