version: 2
jobs:
  compile:
    docker:
      - image: clux/muslrust:nightly
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          key: cargo.registry
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - save_cache:
          key: cargo.registry
          paths:
            - /root/.cargo
  build:
    steps:
      - checkout
      - restore_cache:
          key: target-{{ checksum "Cargo.lock" }}
      - docker build -t clux/webapp-rs .
  test:
    docker:
      - image: clux/webapp-rs
          environment:
            DATABASE_URL: postgres://root@localhost/circle_test
      - image: circleci/postgres:9-alpine-ram
    working_directory: /volume
    steps:
      - checkout
      - make test

# TODO: clippy + rustfmt on merge
